project/project/routes.py
from flask import *
from project import db
from project.model import Users,Handler, Rooms, Room_allotted, Drafts,Hotels,Facilities
from project.forms import UserLoginForm, RegisterForm, RoomBookForm, checkOutForm
from flask_login import login_user, current_user, logout_user, login_required
from project.picture_handler import add_profile_pic
import stripe
import os
from project.script import name,address 
from sqlalchemy import and_
from datetime import datetime
from werkzeug.urls import url_parse
# print(hotel_info)

admin = Blueprint('admin',__name__)

stripe_keys = {
  'publishable_key': "pk_test_EzB9rTKHvSb9uZwjzbv8q6kz00tdsUMFq0",
  'secret_key': "sk_test_SHwhbYRWt8S9ff2PfHhLthwq00M7u3Yppv"
}

stripe.api_key = stripe_keys['secret_key']

@admin.route('/')
def index():
    # db.drop_all()
    # db.create_all()
    return render_template('index.html')

# users area #####################################################################

@admin.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('admin.index'))

def facilities_function():
    x = Facilities.query.all()
    L = []
    for x in x :
        facilities = {}
        if x.gym is True:
            facilities['gym'] = True
        if x.FoodBeverages is True:
            facilities['FoodBeverages'] = True
        if x.Parking is True:
            facilities['Parking'] = True  
        if x.Tv is True:
            facilities['Tv'] = True
        if x.wifi is True:
            facilities['wifi'] = True 
        L.append(facilities)  
    return L


@admin.route('/book')
def Book(): 
    recommendations = []
    if not current_user.is_anonymous:
        recommendations = recommendation_function()
    L = facilities_function()
    # print(recommendations)
    return render_template('book.html',hotel_names = name, hotel_address = address, facilities_list = L,recommendations = recommendations)

@admin.route('/signup', methods=['GET', 'POST'])
def signup():
    # if current_user.is_authenticated:
        # return redirect(url_for('admin.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        user = Users(userId=form.userId.data, name=form.name.data,password = form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('admin.index'))
    return render_template('signup.html', title='Register', form=form)


# @admin.route('/userlogin', methods=['GET', 'POST'])
# def UserLogin():
#     # if current_user.is_authenticated:
#         # return redirect(url_for('admin.index'))
#     form = UserLoginForm()
#     if form.validate_on_submit():
#         user = Users.query.filter_by(userId = form.userId.data).first()
#         if user is not None and user.check_password(form.password.data):
#             flash('Logged in successfully.')
#             login_user(user)
#             return redirect(url_for('admin.index'))
#         else:
#             flash('Invalid Credentials')
#             # return render_template(url_for('admin.UserLogin'))
#             return render_template('userlogin.html',form=form)
#     return render_template('userlogin.html', form=form)


@admin.route('/userlogin', methods=['GET', 'POST'])
def UserLogin():
    # if current_user.is_authenticated:
        # return redirect(url_for('admin.index'))
    form = UserLoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(userId = form.userId.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid Credentials')
            return render_template('userlogin.html',form=form)
        # flash('Logged in successfully.')
        login_user(user)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('admin.index')
        return redirect(next_page)
         # return render_template(url_for('admin.UserLogin'))
    return render_template('userlogin.html', form=form)


@admin.route('/<hotelId>/book_info', methods=['GET', 'POST'])
# @login_required
def book_info(hotelId):
    if not current_user.is_authenticated:
        return redirect(url_for('admin.UserLogin'))
    # y = 'H'+hotelId
    # print(y)
    draftRooms = Drafts.query.filter_by(hotelId = hotelId,userId = current_user.userId)
    # print(draftRooms)
    draftList = []
    for each in draftRooms:
        draftList.append(each.roomNo)
    print(draftList)
    rooms = Rooms.query.filter_by(hotelId = hotelId)
    list = []
    for x in rooms:
        list.append({
            'hotelId':x.hotelId,
            'roomNo':x.roomNo,
            'capacity':x.capacity,
            'price':x.price,
            'status':x.status}
        )
    print(len(list))
    return render_template('book_info.html',list = list,draftList = draftList)

data = {}

@admin.route('/<hotelId>/<roomNo>/book_room', methods=['GET', 'POST'])
def book_room(hotelId,roomNo):
    if not current_user.is_authenticated:
        return redirect(url_for('admin.UserLogin'))
    form = RoomBookForm()
    if form.validate_on_submit():

        date_format = "%d/%m/%Y"
        print(type(form.checkIn.data))
        a = datetime.strptime( str(form.checkIn.data), date_format)
        b = datetime.strptime( str(form.checkOut.data), date_format)
        delta = b - a
        total_days =  delta.days

        rate_string = Rooms.query.filter_by(hotelId = hotelId, roomNo = roomNo).first().price
        rate = ''.join(filter(lambda i: i.isdigit(), rate_string)) 
        rate = int(rate)

        amount = rate * total_days
        print(amount,type(amount))
        data['hotelId'] = hotelId
        data['roomNo'] =  roomNo
        data['checkIn'] = form.checkIn.data
        data['checkOut'] = form.checkOut.data
        data['totalMembers'] = form.totalMembers.data
        data['amount'] = amount
        data['days'] = total_days
        data['rate'] = rate
        data['amount'] = amount
    
        return render_template('payment.html',data = data,key = stripe_keys['publishable_key'])
    return render_template('book_room.html', title = 'Book_room', form=form)   


# user area ends  ################################################################

####### for payment ###############

# @admin.route('/<dict>/paymentpage')
# def paymentpage(dict):
#     return render_template('payment.html', dict = dict, key=stripe_keys['publishable_key'])


@admin.route('/<amount>/payment', methods=['GET', 'POST'])
def payment(amount):
    # calculating total days

    # date_format = "%d/%m/%Y"
    # a = datetime.strptime( str(dict['checkIn']), date_format)
    # b = datetime.strptime( str(dict['checkOut']), date_format)
    # delta = b - a
    # total_days =  delta.days
    # print(days)

    # # calculating price rate of room

    # rate_string = Rooms.query.filter_by(hotelId = dict['hotelId'], roomNo = dict['roomNo']).first().price
    # rate = ''.join(filter(lambda i: i.isdigit(), rate_string)) 
    # rate = int(rate)
    # print(rate)

    # total_amount = rate * total_days   # total amount to be paid
    # print(amount)

    # print(dict['hotelId'])
    
    # CUSTOMER INFORMATION
    customer = stripe.Customer.create(email=request.form['stripeEmail'],
                                      source=request.form['stripeToken'])
    
    # CHARGE/PAYMENT INFORMATION
    # amount =Room_allotted.query.filter_by(roomNo = roomNo, hotelId = hotelId).first().amount    
    charge = stripe.Charge.create(
        customer=customer.id,
        amount = amount,
        currency='inr',
        description='Fee'
    )    

    # allot_room = Room_allotted(
    #                         roomNo = dict['roomNo'], 
    #                         hotelId = dict['hotelId'],
    #                         userId = current_user.userId,
    #                         checkIn = dict['checkIn'] , 
    #                         chechOut = dict['checkOut'], 
    #                         totalMembers = dict['totalMembers'])

    # db.session.add(allot_room)
    # db.session.commit()
    # Rooms.query.filter_by(roomNo = dict['roomNo'], hotelId = dict['hotelId']).first().status = False
    # db.session.commit()
    # x = dict['hotelId']
    # print(hotelId)
    return redirect(url_for('admin.saveData'))

@admin.route('/saveData', methods=['GET', 'POST'])
def saveData():
    hotelId = data['hotelId']
    roomNo = data['roomNo']

    allot_room = Room_allotted(
                            roomNo = data['roomNo'], 
                            hotelId = data['hotelId'],
                            userId = current_user.userId,
                            checkIn = data['checkIn'] , 
                            chechOut = data['checkOut'], 
                            totalMembers = data['totalMembers'],
                            days = data['days'],
                            rate = data['rate'],
                            amount = data['amount'])

    db.session.add(allot_room)
    db.session.commit()

    x = Rooms.query.filter_by(roomNo = roomNo, hotelId = hotelId).first()
    if x is not None:
        x.status = False
        db.session.commit()

    y = Room_allotted.query.filter_by(roomNo = roomNo, hotelId = hotelId).first()
    if y is not None:
        y.paymentStatus = True
        db.session.commit()

    z = Drafts.query.filter_by(roomNo = roomNo, hotelId = hotelId, userId = current_user.userId).first()
    if z is not None:
        z.paymentStatus = True
        db.session.commit()
    else:
        draft = Drafts(
                        hotelId = data['hotelId'],
                        userId = current_user.userId,
                        checkIn = data['checkIn'] , 
                        chechOut = data['checkOut'], 
                        totalMembers = data['totalMembers'],
                        roomNo = data['roomNo'], 
                        days = data['days'],

project/project/templates/adminLogin.html
{% extends "base.html" %}

{% block content %}
    <h1>Admin Login</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.userId.label }}<br>
            {{ form.userId(size=32) }}<br>
            {% for error in form.userId.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>

        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

project/project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>SuplSyst</title>

    <!-- bootstrap.css Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- bootstrap.js files -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- water.css file -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.min.css">
   

  </head>
  
<body>
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <li>{{ message }}</li>
  </div>
  {% endfor %}
</ul>
{% endif %}
{% endwith %}
    

<div class="container">
  {% block content %}

  {% endblock %}
</div>
  </body>
</html>

project/project/templates/book.html
<!--

=========================================================
* Now UI Kit - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-kit
* Copyright 2019 Creative Tim (http://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/now-ui-kit/blob/master/LICENSE.md)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Hotel Registration
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/now-ui-kit.css')}}"/>
</head>

<body class="landing-page sidebar-collapse">
  <!-- Navbar -->
  <!-- <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-header">Dropdown header</a>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">One more separated link</a>
        </div>
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" href="https://demos.creative-tim.com/now-ui-kit/index.html" rel="tooltip" title="Designed by Invision. Coded by Creative Tim" data-placement="bottom" target="_blank">
          Now Ui Kit
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="../index.html">Back to Kit</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/creativetimofficial/now-ui-kit/issues">Have an issue?</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank">
              <i class="fab fa-twitter"></i>
              <p class="d-lg-none d-xl-none">Twitter</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank">
              <i class="fab fa-facebook-square"></i>
              <p class="d-lg-none d-xl-none">Facebook</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank">
              <i class="fab fa-instagram"></i>
              <p class="d-lg-none d-xl-none">Instagram</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav> -->
  <!-- End Navbar -->

  <nav class="navbar navbar-expand-lg bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link" href="{{url_for('admin.index')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('admin.Book')}}">Booking</a>
            </li>
            {% if current_user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.signup')}}">Signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.UserLogin')}}">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('admin.adminLogin')}}">Admin</a>
              </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.userDashboard')}}">Dashboard</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.recommended')}}">Recommended</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.logout')}}">Logout</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    {% for x in range(0,22) %}
        <div class="card" style="width: 25rem;height:20rem ;"> 
            <div class="card-body">
                <h4 class="card-title">{{hotel_names[x]}}</h4>     
              <h6 class="card-subtitle mb-2 text-muted">{{hotel_address[x]}}</h6>
              {% if recommendation is defined%}

              {% else%}
                {% if x in recommendations %}
                &nbsp;&nbsp;
                <h6>Recommended for You </h6>
                {% endif %}
             {% endif %}
              <p> 
                  {% if facilities_list[x]['gym'] == true %}
                      Gym &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['FoodBeverages'] == true %}
                      Food & Beverages &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['Parking'] == true %}
                      Parking Facility &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['Tv'] == true %}
                      TV &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['wifi'] == true %}
                      Free Wi-fi &nbsp;&nbsp;
                  {% endif %}
             </p> 
              <p class="card-text"></p>
              <a href="{{url_for('admin.book_info', hotelId = 'H' + (x)|string )}}" class="card-link">View Rooms</a>
            </div>
        </div>
        <br>
    {% endfor %}
    </div>




    <!-- hotel ends -->
    <footer class="footer footer-default">
      <div class=" container ">
        <nav>
          <ul>
           
          </ul>
        </nav>
        <div class="copyright" id="copyright">
          &copy;
          <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
          </script>, Made with &hearts;!
        </div>
      </div>
    </footer>
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='js/core/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/popper.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/bootstrap.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-switch.js')}}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{url_for('static', filename='js/plugins/nouislider.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-datepicker.js')}}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='js/now-ui-kit.js')}}" type="text/javascript"></script>
</body>

</html>

project/project/templates/book_info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Hotel Registration
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/now-ui-kit.css')}}"/>
</head>

<body class="landing-page sidebar-collapse">
 
  <nav class="navbar navbar-expand-lg bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link" href="{{url_for('admin.index')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admin.Book')}}">Booking</a>
          </li>
          {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.signup')}}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.UserLogin')}}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.adminLogin')}}">Admin</a>
            </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.userDashboard')}}">Dashboard</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admin.recommended')}}">Recommended</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.logout')}}">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    <!-- hotels -->

    <div class="container">
        <br>
        <br>
            <div class="card">              
                <div class="card-body">
                <h4 class="card-title"></h4>
                <div class="table-responsive">
                        <table class="table">
                                <thead class=" text-primary">
                                        <tr>
                                            <th>Room NO.</th>
                                            <th>Capacity</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                
                                <tbody>
                                {% for each in list %}
                                    <tr>
                                        <td>{{each['roomNo']}}</td>
                                        <td>{{each['capacity']}}</td>
                                        <td>{{each['price']}}</td>
                                        {% if each['status'] == false %}
                                            <td>Already booked</td>
                                        {% elif each['roomNo'] in draftList %}
                                        <td>
                                          <p>Draft Saved</p>
                                          <a href="{{url_for('admin.viewDraft')}}">View draft</a>
                                          </td>
                                        {% elif each['status'] == true %}
                                            <td>
                                            <p>Available</p>
                                            <a href="{{url_for('admin.book_room', hotelId = each['hotelId'] , roomNo = each['roomNo'])}}">Book Room</a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                                </table>    
                </div>
                </div>
            </div> 
    </div>




    <!-- hotel ends -->
    <footer class="footer footer-default">
      <div class=" container ">
        <nav>
          <ul>
           
          </ul>
        </nav>
        <div class="copyright" id="copyright">
          &copy;
          <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
          </script>, Made with &hearts;!
        </div>
      </div>
    </footer>
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='js/core/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/popper.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/bootstrap.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-switch.js')}}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{url_for('static', filename='js/plugins/nouislider.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-datepicker.js')}}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='js/now-ui-kit.js')}}" type="text/javascript"></script>
</body>

</html>